config/routes.rb
Rails.application.routes.draw do
  #resources :posts
  get 'posts/index'
  get 'sessions/new'
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources  :users

  resources :posts do
  collection do
    post :confirm
  end
  end

  resources :favorites, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: {maximum: 140}
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :avatar, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                     before_validation { email.downcase! }
                    has_secure_password
                    validates :password, presence: true, length: { minimum: 6 }
                    has_many :posts
                    has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}'S blog has been added to favorites"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}Unblogged Mr.'s blog"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  # end
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def edit

  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    #@post = Post.new(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "i post a blog！"
      else
        render :new
      end
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "I edited the blog!"
    else
      render :edit
    end
  end

  def set_post
      @post = Post.find(params[:id])
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice:"I deleted the blog!"
  end

  def confirm
      @post = current_user.posts.build(post_params)
      #@post = Post.new(post_params)
      render :new if @post.invalid?
  end

  private
  def post_params
     params.require(:post).permit(:content,:avatar, :avatar_cache)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'connection echoue'
      render :new
  end
  end

  def destroy
     session.delete(:user_id)
     flash[:notice] = 'logged out'
     redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def show
       @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
      redirect_to user_path(@user.id)
      else
        render :new
      end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)

    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
  if action_name == 'new' || action_name == 'create'
    confirm_posts_path
  elsif action_name == 'edit'
    post_path
  end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kouisine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">  <!-- head内にこのタグ設定を追記する -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id) %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>There are errors.</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div> <br>
  <% end %>

  <div class="post_content" maxlength ="140">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div> <br>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.avatar.url) if @post.avatar && @post.avatar.url %>
    <%= form.file_field :avatar %>
    <%= form.hidden_field :avatar_cache %>
  </div><br>
  <%= form.submit %>
<% end %> <br>
<%= link_to " Retour à la liste des blogs", posts_path %>

app/views/posts/confirm.html.erb
<h3>these data are going to be sent</h3>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>

<div class="post_content">
  <%= form.label :content %>
  <%= form.text_area :content %>
</div> <br>

<div>
  <%= image_tag(@post.avatar.url) if @post.avatar && @post.avatar.url %>
  <%= form.hidden_field :avatar_cache %>
</div>

<%= form.submit  "Registre" %>
  <%= form.submit "戻る" , name: 'back'%>
<% end %>

<%= link_to 'Back', :back %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>

  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div> <br>
  <%= form.submit %>
    <% end %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>MBlogs Dive</title>
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/sample.css">
</head>
<body background-color:red>
  <header class="header clearfix">

    <ul class="menu_horizontal">
		<li class="bouton_gauche"><a href="#">Blogs Dive</a></li>

    </ul>
  </header>

  <h1 id="title">All blogs list</h1>

  <p><%= notice %></p>

  <% @posts.each do |post| %>

    <%= post.created_at %><p><b>Posted by:</b> <%= post.user.name %></p>

    <textarea id="w3review" name="w3review" rows="4" cols="25" maxlength="140">
      <%= post.content %>
    </textarea>   <br>
    <%= image_tag(post.avatar_url,style:'width:300px;height:200px') if post.avatar_url %><br>

    <%= link_to 'Show', post %>
    <a href="<%= edit_post_path(post.id) %> " class="bt-btn-primary">Edit</a>

    <td><%= link_to 'Delete post', post_path(post.id), method: :delete,data: { confirm: 'Can I really edit it?' } %></td>

    <br>
  <% end %>
  <br>
<%= link_to 'Post a new blog', new_post_path %>

</body>
</html>

app/views/posts/new.html.erb
<h2>Create a blog</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post_content">
  <strong>Content</strong>
  <%= @post.content %>
</div>

<div>
  <strong>Image:</strong>
 <%= image_tag(@post.avatar_url,style:'width:100px;height:1000px') if @post.avatar_url %>
</div>

<% unless @post.user_id == current_user.id %>
<% if @favorite.present? %>1
  <%= link_to 'Remove favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
<% end %>
<% end %>

<%= link_to 'Back to posts', posts_path %>

app/views/posts1/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>MBlogs Dive</title>
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/sample.css">
</head>
<body>
  <header class="header clearfix">

    <ul class="menu_horizontal">
		<li class="bouton_gauche"><a href="#">Blogs Dive</a></li>
    </ul>
  </header>

  <h1>All blogs list</h1>

  <p><%= notice %></p>

  <% @users.each do |user| %>


    <label for="">Date de creation du blog:</label> <%= user.created_at %> <br>

<textarea id="w3review" name="w3review" rows="4" cols="25" maxlength="140">

  <%= user.name %>
  <%= user.email %>

</textarea> <br>
<p><b>Posted by:</b> <%= user.name %></p>
<a href="<%= edit_user_path(user.id) %> " class="bt-btn-primary">Edit</a>

<td><%= link_to 'Delete post', user_path(user.id), method: :delete,data: { confirm: 'Can I really edit it?' } %></td>

<br>
  <% end %>

  <br>
<%= link_to 'Post a new blog', new_user_path %>

</body>
</html>

app/views/users/new.html.erb
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <%= form_with(model: @user, local: true) do |f| %>

  <table>
    <tr>
      <td> <%= f.label :name %></td>
      <td> <%= f.text_field :name %></td>
    </tr>
    <tr>
      <td> <%= f.label :email %></td>
      <td>
       <%= f.email_field :email %></td>
    </tr>
    <tr>
      <td> <%= f.label :password %></td>
      <td> <%= f.password_field :password %></td>
    </tr>
    <tr>
      <td> <%= f.label :password_confirmation %></td>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
  </table>

 <%= f.submit "Create my account" %>
 <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> page of</h1>
<p>E-mail address: <%= @user.email %></p>